/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef map_CONSTANTS_H
#define map_CONSTANTS_H

#include "map_types.h"



class mapConstants {
 public:
  mapConstants();

};

extern const mapConstants g_map_constants;



#endif
