/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef struct_CONSTANTS_H
#define struct_CONSTANTS_H

#include "struct_types.h"



class structConstants {
 public:
  structConstants();

};

extern const structConstants g_struct_constants;



#endif
